#!/usr/bin/env bash
set -euo pipefail

BASE_BRANCH="${BASE_BRANCH:-main}"
MAX_PRS="${MAX_PRS:-20}"
ROLLUP_BRANCH_PREFIX="${ROLLUP_BRANCH_PREFIX:-codex/dependabot-rollup}"
OPENAI_MODEL="${OPENAI_MODEL:-gpt-4.1-mini}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

rollup_branch="${ROLLUP_BRANCH_PREFIX}-$(date +%Y%m%d)"

echo "Base branch: ${BASE_BRANCH}"
echo "Rollup branch: ${rollup_branch}"
echo "Max PRs: ${MAX_PRS}"

git fetch origin "${BASE_BRANCH}" --quiet
git checkout -B "${rollup_branch}" "origin/${BASE_BRANCH}"

pr_json="$(gh pr list \
  --repo "${GITHUB_REPOSITORY}" \
  --state open \
  --base "${BASE_BRANCH}" \
  --limit 100 \
  --json number,title,headRefName,author,url \
  --jq 'map(select((.author.login | ascii_downcase | test("(^dependabot(\\[bot\\])?$)|(^app/dependabot$)|(^dependabot bot$)")) or (.headRefName | ascii_downcase | startswith("dependabot/")) ))')"

selected_json="$(echo "${pr_json}" | jq ".[:${MAX_PRS}]")"
selected_count="$(echo "${selected_json}" | jq 'length')"

if [[ "${selected_count}" -eq 0 ]]; then
  echo "No open Dependabot PRs against ${BASE_BRANCH}."
  {
    echo "merged_count=0"
    echo "rollup_branch=${rollup_branch}"
  } >> "${GITHUB_OUTPUT}"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

merged_lines=()
skipped_lines=()
merged_items_json='[]'

for number in $(echo "${selected_json}" | jq -r '.[].number'); do
  pr="$(echo "${selected_json}" | jq ".[] | select(.number==${number})")"
  title="$(echo "${pr}" | jq -r '.title')"
  head="$(echo "${pr}" | jq -r '.headRefName')"
  url="$(echo "${pr}" | jq -r '.url')"

  echo "Processing #${number} (${head}): ${title}"

  if ! git fetch origin "${head}" --quiet; then
    skipped_lines+=("- #${number} (${head}): fetch failed")
    continue
  fi

  if git merge --no-ff --no-edit "origin/${head}"; then
    merged_lines+=("- #${number}: ${title}")
    merged_items_json="$(echo "${merged_items_json}" | jq --arg n "${number}" --arg t "${title}" --arg h "${head}" --arg u "${url}" '. + [{number:$n,title:$t,head:$h,url:$u}]')"
  else
    git merge --abort || true
    git reset --hard "HEAD" >/dev/null 2>&1
    skipped_lines+=("- #${number}: ${title} (merge conflict)")
  fi
done

merged_count="${#merged_lines[@]}"
if [[ "${merged_count}" -eq 0 ]]; then
  echo "No Dependabot PRs were mergeable; stopping."
  {
    echo "merged_count=0"
    echo "rollup_branch=${rollup_branch}"
  } >> "${GITHUB_OUTPUT}"
  exit 0
fi

git push --force-with-lease origin "${rollup_branch}"

merged_md="$(printf '%s\n' "${merged_lines[@]}")"
skipped_md=""
if [[ "${#skipped_lines[@]}" -gt 0 ]]; then
  skipped_md="$(printf '%s\n' "${skipped_lines[@]}")"
fi

repo_url="https://github.com/${GITHUB_REPOSITORY}"

summary_text=""
if [[ -n "${OPENAI_API_KEY:-}" ]]; then
  prompt="You are preparing a release-manager summary for a single rollup pull request that merges Dependabot updates.\n\nReturn markdown with exactly these headings:\n## What Changed\n## Risk Notes\n## Suggested Review Order\n\nRules:\n- Keep it concise and practical.\n- Mention likely hotspots where dependency updates can break builds/tests.\n- Use bullet lists only.\n- Do not invent package internals you cannot infer from titles/branch names.\n\nDependabot items:\n$(echo "${merged_items_json}" | jq -r '.[] | "- PR #\(.number): \(.title) [\(.head)]"')"

  payload="$(jq -n \
    --arg model "${OPENAI_MODEL}" \
    --arg input "${prompt}" \
    '{model:$model,input:$input}')"

  response="$(curl -sS https://api.openai.com/v1/responses \
    -H "Authorization: Bearer ${OPENAI_API_KEY}" \
    -H "Content-Type: application/json" \
    -d "${payload}" || true)"

  summary_text="$(echo "${response}" | jq -r '.output_text // empty' 2>/dev/null || true)"
fi

if [[ -z "${summary_text}" ]]; then
  summary_text=$(cat <<'MARKDOWN'
## What Changed
- Batched merge of selected Dependabot PRs into one reviewable rollup.

## Risk Notes
- Lockfile and transitive dependency shifts may affect CI and runtime behavior.
- Multiple dependency bumps together can hide which update caused a regression.

## Suggested Review Order
- Scan majors/minors first, then patch updates.
- Run full CI and smoke critical flows before merge.
MARKDOWN
)
fi

pr_title="chore(deps): dependabot rollup (${merged_count} PRs)"

pr_body_file="$(mktemp)"
{
  echo "This PR batches mergeable Dependabot PRs against \`${BASE_BRANCH}\` into one review."
  echo
  echo "${summary_text}"
  echo
  echo "## Included PRs"
  echo "${merged_md}"
  if [[ -n "${skipped_md}" ]]; then
    echo
    echo "## Skipped PRs"
    echo "${skipped_md}"
  fi
  echo
  echo "---"
  echo "Generated by [dependabot-rollup workflow](${repo_url}/actions/workflows/dependabot-rollup.yml)."
} > "${pr_body_file}"

existing_pr_number="$(gh pr list \
  --repo "${GITHUB_REPOSITORY}" \
  --head "${rollup_branch}" \
  --base "${BASE_BRANCH}" \
  --state open \
  --limit 1 \
  --json number \
  --jq '.[0].number // empty')"

if [[ -n "${existing_pr_number}" ]]; then
  gh pr edit "${existing_pr_number}" \
    --repo "${GITHUB_REPOSITORY}" \
    --title "${pr_title}" \
    --body-file "${pr_body_file}"
  pr_url="$(gh pr view "${existing_pr_number}" --repo "${GITHUB_REPOSITORY}" --json url --jq '.url')"
  echo "Updated existing rollup PR: ${pr_url}"
else
  pr_url="$(gh pr create \
    --repo "${GITHUB_REPOSITORY}" \
    --base "${BASE_BRANCH}" \
    --head "${rollup_branch}" \
    --title "${pr_title}" \
    --body-file "${pr_body_file}")"
  echo "Created rollup PR: ${pr_url}"
fi

{
  echo "merged_count=${merged_count}"
  echo "rollup_branch=${rollup_branch}"
  echo "rollup_pr_url=${pr_url}"
} >> "${GITHUB_OUTPUT}"
