/**
 * Curated text prompts per taxonomy category for CLAP embedding / classification.
 * 20–40 prompts per category. Used for zero-shot or few-shot assignment.
 */

import type { TaxonomyAttributeKey } from "./taxonomy.js";

export const TAXONOMY_PROMPTS: Record<TaxonomyAttributeKey, readonly string[]> = {
  instrument_family: [
    "drum percussion",
    "synthesizer synth",
    "bass instrument",
    "sound effect fx",
    "texture ambient pad",
    "drum kit",
    "electronic synth",
    "bass line",
    "atmospheric fx",
    "textured soundscape",
    "percussion drums",
    "synth pad",
    "bass sound",
    "effect riser",
    "texture layer",
  ],
  instrument_type: [
    "kick drum",
    "snare drum",
    "clap",
    "hi-hat hat",
    "tom drum",
    "cymbal crash",
    "pad synth",
    "lead synth",
    "pluck synth",
    "stab chord",
    "bass synth",
    "riser build",
    "kick 808",
    "rim shot",
    "open hat",
    "closed hat",
    "ride cymbal",
    "atmospheric pad",
    "synth lead",
    "plucky synth",
    "stabbing chord",
    "sub bass",
    "sweep riser",
  ],
  style: [
    "lofi hip hop",
    "techno electronic",
    "house music",
    "cinematic orchestral",
    "trap hip hop",
    "ambient atmospheric",
    "lofi beat",
    "techno industrial",
    "deep house",
    "cinematic epic",
    "trap 808",
    "ambient drone",
    "lofi chill",
    "minimal techno",
    "disco house",
    "film score",
    "trap beat",
    "ambient pad",
  ],
  descriptor: [
    "warm analog",
    "bright crisp",
    "dark moody",
    "punchy transient",
    "dusty vinyl",
    "metallic harsh",
    "distorted saturated",
    "clean pristine",
    "crunchy lo-fi",
    "wide stereo",
    "dry close",
    "warm saturated",
    "bright sparkly",
    "dark sub",
    "punchy attack",
    "dusty tape",
    "metallic resonance",
    "distorted grit",
    "clean mix",
    "crunchy bitcrush",
    "wide reverb",
    "dry direct",
  ],
  mood: [
    "aggressive intense",
    "soft gentle",
    "uplifting euphoric",
    "tense suspenseful",
    "moody melancholic",
    "aggressive driving",
    "soft ambient",
    "uplifting energetic",
    "tense dramatic",
    "moody dark",
    "aggressive punchy",
    "soft warm",
    "uplifting hopeful",
    "tense anxious",
    "moody introspective",
  ],
};
